### ISSUE TITLE
Build #3 failed

### ISSUE THREAD

**Issue by mtorrisi** [SouthAfricaDigitalScience/matlab-runtime-deploy#3]
it looks like that it doesn't find the zip downloaded in a previous build:
`continuing from previous builds, using source at  /repo/src/matlab-runtime/R2016a/MCR_R2016a_glnxa64_installer.zip
unzip:  cannot find or open MCR_R2016a_glnxa64_installer.zip, MCR_R2016a_glnxa64_installer.zip.zip or MCR_R2016a_glnxa64_installer.zip.ZIP.`

**Comment by brucellino** [comment]
It looks like the file is there : 

`file  /repo/src/matlab-runtime/R2016a/MCR_R2016a_glnxa64_installer.zip 
/repo/src/matlab-runtime/R2016a/MCR_R2016a_glnxa64_installer.zip: Zip archive data, at least v2.0 to extract`

but it has the wrong name - missing an `MCR_` I'll send a PR to fix it soon.
